### ISSUE TITLE
PipelineManager notifications & status

### ISSUE THREAD

**Issue by vreuter** [epigen/pypiper#30]
https://github.com/epigen/pypiper/pull/28#issuecomment-288871230

**Comment by vreuter** [comment]
It sounds like these are related and could be bundled as some notion of a `Messenger` class that's used by `PipelineManager` as you suggested @nsheff . It also seems like any subset of email, HTML logs, and results-to-DB storage would be viable on its own, though. So could such a class take some sort of configuration argument for each one and have its behavior be based on the presence of such a configuration and values therein? What I'm trying to say is that, for example, it seems reasonable to want to create just a `Messenger` (or whatever) for web logs, or just one for DB storage, or one that does email & DB but not logs, etc.

**Comment by nsheff** [comment]
to me this sounds like settings changes to a single object type.

we add a looperenv section called 'notifications' and it can look like this:
```
notifications:
  mail: on_failure
  address: mail@address.com
  database:
    user: username
    password: passwd
    server: mysql.server.address.org
```

pypiper could read a serialized yaml for notifications, which looper could create for each submission (like it does already for sample objects).

HTML version of live logs is related to @afrendeiro 's flask idea for looper; I also talked with @hussainzaidi about the HTML-log idea a bit as well.

have to be careful to keep pypiper and looper loosely coupled, though.
